# Generated by Django 5.0.3 on 2025-04-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='decorated_image',
            field=models.ImageField(upload_to='join_img/'),
        ),
    ]
